from django.urls import path

from .views.dashboard import (
    DashboardAuditLogView,
    DashboardBackupCreateView,
    DashboardBackupDeleteView,
    DashboardBackupListView,
    DashboardBackupVerifyView,
    DashboardStructureBatchView,
    DashboardCommuneCreateView,
    DashboardCommuneDeleteView,
    DashboardCommuneListView,
    DashboardCommuneUpdateView,
    DashboardHomeView,
    DashboardImportView,
    DashboardInscriptionDecideView,
    DashboardInscriptionListView,
    DashboardNotificationAddView,
    DashboardNotificationDeleteView,
    DashboardNotificationListView,
    DashboardNotificationUpdateView,
    DashboardPasswordChangeView,
    DashboardProfileView,
    DashboardStructureCreateView,
    DashboardStructureDeleteView,
    DashboardStructureListView,
    DashboardStructureUpdateView,
    DashboardTypeCreateView,
    DashboardTypeDeleteView,
    DashboardTypeListView,
    DashboardTypeUpdateView,
    DashboardUserCreateView,
    DashboardUserDeleteView,
    DashboardUserListView,
    DashboardUserUpdateView,
)

app_name = "dashboard"

urlpatterns = [
    path("", DashboardHomeView.as_view(), name="home"),
    path("profil/", DashboardProfileView.as_view(), name="profile"),
    path("mot-de-passe/", DashboardPasswordChangeView.as_view(), name="password_change"),
    path("structures/", DashboardStructureListView.as_view(), name="structure_list"),
    path("structures/ajouter/", DashboardStructureCreateView.as_view(), name="structure_add"),
    path("structures/<int:pk>/modifier/", DashboardStructureUpdateView.as_view(), name="structure_edit"),
    path("structures/<int:pk>/supprimer/", DashboardStructureDeleteView.as_view(), name="structure_delete"),
    path("structures/lot/", DashboardStructureBatchView.as_view(), name="structure_batch"),
    path("communes/", DashboardCommuneListView.as_view(), name="commune_list"),
    path("communes/ajouter/", DashboardCommuneCreateView.as_view(), name="commune_add"),
    path("communes/<int:pk>/modifier/", DashboardCommuneUpdateView.as_view(), name="commune_edit"),
    path("communes/<int:pk>/supprimer/", DashboardCommuneDeleteView.as_view(), name="commune_delete"),
    path("types/", DashboardTypeListView.as_view(), name="type_list"),
    path("types/ajouter/", DashboardTypeCreateView.as_view(), name="type_add"),
    path("types/<int:pk>/modifier/", DashboardTypeUpdateView.as_view(), name="type_edit"),
    path("types/<int:pk>/supprimer/", DashboardTypeDeleteView.as_view(), name="type_delete"),
    path("importer/", DashboardImportView.as_view(), name="import_data"),
    path("utilisateurs/", DashboardUserListView.as_view(), name="user_list"),
    path("utilisateurs/ajouter/", DashboardUserCreateView.as_view(), name="user_add"),
    path("utilisateurs/<int:pk>/modifier/", DashboardUserUpdateView.as_view(), name="user_edit"),
    path("utilisateurs/<int:pk>/supprimer/", DashboardUserDeleteView.as_view(), name="user_delete"),
    path("demandes-inscriptions/", DashboardInscriptionListView.as_view(), name="inscription_list"),
    path("demandes-inscriptions/<int:pk>/", DashboardInscriptionDecideView.as_view(), name="inscription_decide"),
    path("notifications/", DashboardNotificationListView.as_view(), name="notification_list"),
    path("notifications/ajouter/", DashboardNotificationAddView.as_view(), name="notification_add"),
    path("notifications/maj/", DashboardNotificationUpdateView.as_view(), name="notification_update"),
    path("notifications/<int:pk>/supprimer/", DashboardNotificationDeleteView.as_view(), name="notification_delete"),
    path("sauvegardes/", DashboardBackupListView.as_view(), name="backup_list"),
    path("sauvegardes/creer/", DashboardBackupCreateView.as_view(), name="backup_create"),
    path("sauvegardes/verifier/<str:name>/", DashboardBackupVerifyView.as_view(), name="backup_verify"),
    path("sauvegardes/supprimer/<str:name>/", DashboardBackupDeleteView.as_view(), name="backup_delete"),
    path("journal/", DashboardAuditLogView.as_view(), name="audit_log"),
]
