# Generated by Django 6.0.7 on 2026-09-08 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bug', 'Bug'), ('suggestion', 'Suggestion'), ('autre', 'Autre remarque')], default='bug', max_length=20, verbose_name='Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('page_auto', models.CharField(blank=True, help_text='Chemin déduit côté serveur (Referer), non modifiable.', max_length=500, verbose_name='Page détectée')),
                ('page_declaree', models.CharField(help_text="Page indiquée par l'utilisateur (pré-remplie, modifiable).", max_length=500, verbose_name='Page concernée')),
                ('url_name', models.CharField(blank=True, max_length=200, verbose_name="Nom d'URL")),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='Navigateur')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('commentaire_interne', models.TextField(blank=True, verbose_name='Commentaire interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut', '-created_at'], name='feedback_fe_statut_e3d236_idx')],
            },
        ),
    ]
