# Generated by Django 6.0.3 on 2026-09-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackreport',
            name='page_declaree',
            field=models.CharField(blank=True, default='', help_text="Page indiquée par l'utilisateur (pré-remplie, modifiable, facultative).", max_length=500, verbose_name='Page concernée'),
        ),
    ]
