# Generated by Django 6.0.7 on 2026-07-26 13:23

import django.db.models.deletion
import structures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Type de structure',
                'verbose_name_plural': 'Types de structure',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_monenfant', models.BooleanField(default=True, verbose_name='Référencé monenfant.fr')),
                ('date_mise_a_jour', models.DateField(auto_now=True, verbose_name='Date de mise à jour')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('age_non_renseigne', models.BooleanField(default=False, verbose_name='Âge non renseigné')),
                ('age_min', models.IntegerField(blank=True, null=True, verbose_name='Âge minimum')),
                ('age_min_unite', models.CharField(blank=True, choices=[('semaine', 'semaine(s)'), ('mois', 'mois'), ('ans', 'an(s)')], max_length=10, verbose_name='Unité âge min')),
                ('age_max', models.IntegerField(blank=True, null=True, verbose_name='Âge maximum')),
                ('age_max_unite', models.CharField(blank=True, choices=[('semaine', 'semaine(s)'), ('mois', 'mois'), ('ans', 'an(s)')], max_length=10, verbose_name='Unité âge max')),
                ('horaires', models.JSONField(default=structures.models.horaires_default, verbose_name='Horaires par jour')),
                ('horaires_notes', models.TextField(blank=True, verbose_name='Notes horaires')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('places_disponibles', models.IntegerField(blank=True, null=True, verbose_name='Places disponibles')),
                ('places_complet', models.BooleanField(default=False, verbose_name='Complet')),
                ('places_non_communique', models.BooleanField(default=False, verbose_name='Non communiqué')),
                ('conditions_places', models.TextField(blank=True, verbose_name='Conditions places disponibles')),
                ('nb_places_total', models.IntegerField(blank=True, null=True, verbose_name='Nombre de places total')),
                ('accueil_handicap', models.BooleanField(blank=True, null=True, verbose_name='Accueil handicap')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('directeur', models.CharField(blank=True, max_length=255, verbose_name='Directeur/trice')),
                ('tel_direction', models.CharField(blank=True, max_length=50, verbose_name='Tél. direction')),
                ('email_direction', models.EmailField(blank=True, max_length=254, verbose_name='Email direction')),
                ('statut', models.CharField(blank=True, max_length=100, verbose_name='Statut')),
                ('aides', models.CharField(blank=True, max_length=255, verbose_name='Aides')),
                ('nb_professionnels', models.IntegerField(blank=True, null=True, verbose_name='Nb professionnel·les')),
                ('recrutement', models.BooleanField(blank=True, null=True, verbose_name='Recrutement en cours')),
                ('accueil_urgence', models.BooleanField(blank=True, null=True, verbose_name="Accueil d'urgence")),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communes.commune', verbose_name='Commune')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.typestructure', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
                'ordering': ['nom'],
            },
        ),
    ]
