# Generated by Django 6.0.7 on 2026-07-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='date_mise_a_jour_monenfant',
            field=models.DateField(blank=True, null=True, verbose_name='Date mise à jour monenfant.fr'),
        ),
    ]
