# Generated by Django 6.0.7 on 2026-07-27 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_structure_date_mise_a_jour_monenfant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('batch', 'Action groupée'), ('import', 'Import')], max_length=20, verbose_name='Action')),
                ('model_name', models.CharField(max_length=50, verbose_name='Modèle')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Représentation')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Modifications')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-timestamp'],
            },
        ),
    ]
