# Generated by Django 6.0.7 on 2026-07-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0004_structure_latitude_structure_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='afficher',
            field=models.BooleanField(default=True, verbose_name='Afficher sur le site'),
        ),
    ]
