# Generated by Django 6.0.7 on 2026-08-17.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structures", "0005_structure_afficher"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("places_disponibles__isnull", True),
                    ("places_disponibles__gte", 0),
                    _connector="OR",
                ),
                name="structure_places_disponibles_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("nb_places_total__isnull", True),
                    ("nb_places_total__gte", 0),
                    _connector="OR",
                ),
                name="structure_places_total_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("nb_professionnels__isnull", True),
                    ("nb_professionnels__gte", 0),
                    _connector="OR",
                ),
                name="structure_professionnels_positifs",
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("age_min__isnull", True),
                    ("age_min__gte", 0),
                    _connector="OR",
                ),
                name="structure_age_min_positif",
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("age_max__isnull", True),
                    ("age_max__gte", 0),
                    _connector="OR",
                ),
                name="structure_age_max_positif",
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("places_complet", True),
                    ("places_non_communique", True),
                    _negated=True,
                ),
                name="structure_places_statuts_coherents",
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("places_disponibles__isnull", True),
                    ("nb_places_total__isnull", True),
                    ("places_disponibles__lte", models.F("nb_places_total")),
                    _connector="OR",
                ),
                name="structure_places_disponibles_lte_total",
            ),
        ),
    ]
