# Generated by Django 6.0.7 on 2026-08-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0001_initial'),
        ('structures', '0006_structure_data_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='date_mise_a_jour',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='date_mise_a_jour_monenfant',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Date mise à jour monenfant.fr'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['afficher', 'date_mise_a_jour'], name='structure_visible_recent'),
        ),
    ]
