# Generated by Django 6.0.7 on 2026-08-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0007_alter_structure_date_mise_a_jour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['nom_structure', 'nom', 'prenom'], 'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.AddField(
            model_name='structure',
            name='nom_structure',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de la structure'),
        ),
        migrations.AddField(
            model_name='structure',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='nom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom'),
        ),
    ]
