# Generated by Django 6.0.3 on 2026-09-11 06:12

from django.db import migrations, models


def remplir_nb_professionnels_vides(apps, schema_editor):
    Structure = apps.get_model("structures", "Structure")
    Structure.objects.filter(nb_professionnels__isnull=True).update(nb_professionnels=1)


def annuler_remplissage_nb_professionnels(apps, schema_editor):
    # Remplissage non réversible : on laisse les valeurs saisies telles quelles.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0010_auditlog_structures_auditlog_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='aides',
        ),
        migrations.AddField(
            model_name='structure',
            name='commentaire_interne',
            field=models.TextField(blank=True, verbose_name='Commentaire interne'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='nb_professionnels',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Nb professionnel·les'),
        ),
        migrations.RunPython(
            remplir_nb_professionnels_vides,
            annuler_remplissage_nb_professionnels,
        ),
    ]
