# Generated by Django 6.0.3 on 2026-09-11 07:56

from django.db import migrations, models
from django.db.models import F


def reporter_places_vers_agrement_pmi(apps, schema_editor):
    """Report des valeurs existantes vers le « temps complet ».

    Le découpage temps complet / périscolaire n'existait pas avant :
    tout l'historique est rattaché au temps complet, le périscolaire
    reste vide (NULL) et pourra être renseigné fiche par fiche.
    """
    Structure = apps.get_model("structures", "Structure")
    Structure.objects.filter(nb_places_total__isnull=False).update(
        agrement_pmi_temps_complet=F("nb_places_total")
    )
    Structure.objects.filter(places_disponibles__isnull=False).update(
        places_disponibles_temps_complet=F("places_disponibles")
    )


def restaurer_places_depuis_agrement_pmi(apps, schema_editor):
    """Retour arrière : recopie le « temps complet » vers les anciens champs."""
    Structure = apps.get_model("structures", "Structure")
    Structure.objects.filter(agrement_pmi_temps_complet__isnull=False).update(
        nb_places_total=F("agrement_pmi_temps_complet")
    )
    Structure.objects.filter(places_disponibles_temps_complet__isnull=False).update(
        places_disponibles=F("places_disponibles_temps_complet")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0001_initial'),
        ('structures', '0011_remove_structure_aides_structure_commentaire_interne_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='structure',
            name='structure_places_disponibles_positive',
        ),
        migrations.RemoveConstraint(
            model_name='structure',
            name='structure_places_total_positive',
        ),
        migrations.RemoveConstraint(
            model_name='structure',
            name='structure_places_disponibles_lte_total',
        ),
        migrations.AddField(
            model_name='structure',
            name='agrement_pmi_periscolaire',
            field=models.IntegerField(blank=True, null=True, verbose_name='Agrément PMI périscolaire'),
        ),
        migrations.AddField(
            model_name='structure',
            name='agrement_pmi_temps_complet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Agrément PMI temps complet'),
        ),
        migrations.AddField(
            model_name='structure',
            name='places_disponibles_periscolaire',
            field=models.IntegerField(blank=True, null=True, verbose_name='Places disponibles périscolaire'),
        ),
        migrations.AddField(
            model_name='structure',
            name='places_disponibles_temps_complet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Places disponibles temps complet'),
        ),
        migrations.RunPython(
            reporter_places_vers_agrement_pmi,
            restaurer_places_depuis_agrement_pmi,
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.CheckConstraint(condition=models.Q(('places_disponibles_temps_complet__isnull', True), ('places_disponibles_temps_complet__gte', 0), _connector='OR'), name='structure_dispo_tc_positive'),
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.CheckConstraint(condition=models.Q(('places_disponibles_periscolaire__isnull', True), ('places_disponibles_periscolaire__gte', 0), _connector='OR'), name='structure_dispo_peri_positive'),
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.CheckConstraint(condition=models.Q(('agrement_pmi_temps_complet__isnull', True), ('agrement_pmi_temps_complet__gte', 0), _connector='OR'), name='structure_agrement_tc_positif'),
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.CheckConstraint(condition=models.Q(('agrement_pmi_periscolaire__isnull', True), ('agrement_pmi_periscolaire__gte', 0), _connector='OR'), name='structure_agrement_peri_positif'),
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.CheckConstraint(condition=models.Q(('places_disponibles_temps_complet__isnull', True), ('agrement_pmi_temps_complet__isnull', True), ('places_disponibles_temps_complet__lte', models.F('agrement_pmi_temps_complet')), _connector='OR'), name='structure_dispo_tc_lte_agrement_tc'),
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.CheckConstraint(condition=models.Q(('places_disponibles_periscolaire__isnull', True), ('agrement_pmi_periscolaire__isnull', True), ('places_disponibles_periscolaire__lte', models.F('agrement_pmi_periscolaire')), _connector='OR'), name='structure_dispo_peri_lte_agrement_peri'),
        ),
        migrations.RemoveField(
            model_name='structure',
            name='nb_places_total',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='places_disponibles',
        ),
    ]
