"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = config("SECRET_KEY")

ENVIRONMENT = config("ENVIRONMENT", default="development").lower()
IS_PRODUCTION = ENVIRONMENT == "production"
DEBUG = config("DEBUG", default=not IS_PRODUCTION, cast=bool)

if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured("DEBUG doit être désactivé en production.")

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="127.0.0.1,localhost", cast=Csv())

if IS_PRODUCTION and (not ALLOWED_HOSTS or {"127.0.0.1", "localhost"} & set(ALLOWED_HOSTS)):
    raise ImproperlyConfigured("ALLOWED_HOSTS doit contenir uniquement les domaines de production.")

# Chemin d'accès à l'admin Django, à personnaliser en production pour réduire
# le bruit de reconnaissance automatique.
ADMIN_URL = config("ADMIN_URL", default="gestion-interne/").lstrip("/")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "home",
    "communes",
    "structures",
    "authentication",
    "campagnes",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'app.csp.ContentSecurityPolicyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.seo.NoIndexMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.csp_nonce',
                'app.context_processors.pending_inscriptions',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(config("DATABASE_PATH", default=str(BASE_DIR / "db.sqlite3"))),
        'OPTIONS': {
            'timeout': config("SQLITE_TIMEOUT", default=20, cast=int),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = Path(config("STATIC_ROOT", default=str(BASE_DIR / "staticfiles")))

# WhiteNoise sert les statiques depuis STATIC_ROOT en production, sans
# configuration Apache/Passenger dédiée. Le stockage compressé sert des
# fichiers .gz/.br ; le manifeste n'est pas utilisé pour ne pas exiger les
# sourcemaps absentes des bibliothèques vendored (chart.js, leaflet).
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

AUTHENTICATION_BACKENDS = ["authentication.backends.EmailBackend"]

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default=(
        "django.core.mail.backends.smtp.EmailBackend"
        if IS_PRODUCTION
        else "django.core.mail.backends.console.EmailBackend"
    ),
)
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=10, cast=int)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="nepasrepondre@cc-sudavesnois.fr")
SERVER_EMAIL = config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
SITE_URL = config("SITE_URL", default="https://www.sppe.ccsudavesnois.fr").rstrip("/")

GEOCODE_ENABLED = True
GEOCODE_TIMEOUT = config("GEOCODE_TIMEOUT", default=4, cast=int)

_backup_dir_env = config("BACKUP_DIR", default=None)
if IS_PRODUCTION and not _backup_dir_env:
    raise ImproperlyConfigured("BACKUP_DIR est obligatoire en production.")
BACKUP_DIR = _backup_dir_env or str(BASE_DIR / "backups")
BACKUP_RETENTION = config("BACKUP_RETENTION", default=7, cast=int)

if BACKUP_RETENTION < 1:
    raise ImproperlyConfigured("BACKUP_RETENTION doit être au moins égal à 1.")
if IS_PRODUCTION:
    backup_root = Path(BACKUP_DIR).resolve()
    if backup_root == Path(STATIC_ROOT).resolve():
        raise ImproperlyConfigured("BACKUP_DIR doit être distinct de STATIC_ROOT.")
    database_path = Path(config("DATABASE_PATH", default=str(BASE_DIR / "db.sqlite3"))).resolve()
    if backup_root == database_path.parent:
        raise ImproperlyConfigured("BACKUP_DIR doit être distinct du dossier de la base SQLite.")

if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured("EMAIL_USE_TLS et EMAIL_USE_SSL ne peuvent pas être activés ensemble.")

CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())

if IS_PRODUCTION and not CSRF_TRUSTED_ORIGINS:
    raise ImproperlyConfigured("CSRF_TRUSTED_ORIGINS est obligatoire en production.")
if (
    IS_PRODUCTION
    and EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend"
    and not EMAIL_HOST
):
    raise ImproperlyConfigured("EMAIL_HOST est obligatoire avec le backend SMTP de production.")

# Security — valeurs de développement, forcées en production.
# Définies inconditionnellement pour rester testables et surchargeables.
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=False, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=False, cast=bool)
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = config("SECURE_CONTENT_TYPE_NOSNIFF", default=False, cast=bool)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = config(
    "SECURE_HSTS_SECONDS", default=3600 if IS_PRODUCTION else 0, cast=int
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False, cast=bool
)
SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=False, cast=bool)

if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = "DENY"
PASSWORD_RESET_TIMEOUT = 10800  # 3h

# Content Security Policy : nonce par requête, fourni par app.csp.
# Les scripts inline des templates portent ce nonce.
# 'unsafe-inline' reste nécessaire en style-src pour les attributs style
# présents dans les templates ; script-src reste strict via nonce.
CSP_ENABLED = config("CSP_ENABLED", default=True, cast=bool)
CSP_POLICY = (
    "default-src 'self'; "
    "script-src 'self' 'nonce-%(nonce)s'; "
    "style-src 'self' 'unsafe-inline'; "
    "img-src 'self' data: https://*.tile.openstreetmap.org; "
    "font-src 'self'; "
    "connect-src 'self'; "
    "object-src 'none'; "
    "base-uri 'self'; "
    "form-action 'self'; "
    "frame-ancestors 'none'"
)

# Politique de l'admin Django : les templates internes de Django contiennent
# des scripts inline sans nonce, impossibles à réécrire. L'admin garde une
# politique assouplie sur les scripts mais les directives de confinement
# (frame-ancestors, object-src, base-uri, form-action, connect-src) s'appliquent.
CSP_ADMIN_POLICY = (
    "default-src 'self'; "
    "script-src 'self' 'unsafe-inline'; "
    "style-src 'self' 'unsafe-inline'; "
    "img-src 'self' data:; "
    "font-src 'self'; "
    "connect-src 'self'; "
    "object-src 'none'; "
    "base-uri 'self'; "
    "form-action 'self'; "
    "frame-ancestors 'none'"
)

# Rate limiting
RATELIMIT_ENABLE = config("RATELIMIT_ENABLE", default=True, cast=bool)
RATELIMIT_USE_CACHE = "ratelimit"
RATELIMIT_FAIL_OPEN = False

REDIS_URL = config("REDIS_URL", default="")
if IS_PRODUCTION and not REDIS_URL:
    raise ImproperlyConfigured("REDIS_URL est obligatoire en production pour le rate limiting.")

if REDIS_URL:
    INSTALLED_APPS.append("django_ratelimit")
    redis_options = {
        "CLIENT_CLASS": "django_redis.client.DefaultClient",
        "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        "SOCKET_CONNECT_TIMEOUT": 3,
        "SOCKET_TIMEOUT": 3,
    }
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "bddpe",
            "OPTIONS": dict(redis_options),
        },
        "ratelimit": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "bddpe-ratelimit",
            "OPTIONS": dict(redis_options),
        },
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "bddpe-development",
        },
        "ratelimit": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "bddpe-ratelimit-development",
        },
    }

LOG_LEVEL = config("LOG_LEVEL", default="INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{asctime} {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
}
