# Generated by Django 6.0.7 on 2026-08-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinataireNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('actif', models.BooleanField(default=True, verbose_name='Recevoir les notifications')),
                ('en_cci', models.BooleanField(default=False, help_text="L'adresse est placée en copie cachée au lieu des destinataires principaux.", verbose_name='En copie cachée (CCI)')),
            ],
            options={
                'verbose_name': 'Destinataire de notification',
                'verbose_name_plural': 'Destinataires de notifications',
                'ordering': ['email'],
            },
        ),
    ]
