# Generated by Django 6.0.7 on 2026-08-21 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0008_alter_structure_options_structure_nom_structure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('starts_at', models.DateField(verbose_name='Date de début')),
                ('ends_at', models.DateField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('cloturee', 'Clôturée'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('message', models.TextField(blank=True, verbose_name="Message d'introduction")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Campagne de mise à jour',
                'verbose_name_plural': 'Campagnes de mise à jour',
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('confirmation', 'Confirmation sans modification'), ('modification', 'Proposition de modification'), ('arret_activite', "N'exerce plus cette activité"), ('fiche_incorrecte', 'Cette fiche ne me concerne pas')], max_length=30, verbose_name='Type de demande')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('courrier', 'Courrier'), ('telephone', 'Téléphone'), ('accueil', 'Accueil physique')], max_length=20, verbose_name='Canal')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de décision')),
                ('review_comment', models.TextField(blank=True, verbose_name='Commentaire interne')),
                ('created_by', models.ForeignKey(blank=True, help_text='Renseigné lorsque la demande est saisie au nom de la personne.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par un agent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Demande de mise à jour',
                'verbose_name_plural': 'Demandes de mise à jour',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateRequestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Champ')),
                ('old_value', models.TextField(blank=True, verbose_name='Valeur actuelle')),
                ('new_value', models.TextField(blank=True, verbose_name='Valeur proposée')),
                ('decision', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Décision')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='campagnes.updaterequest', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Champ proposé',
                'verbose_name_plural': 'Champs proposés',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='VerificationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Empreinte du jeton')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration du jeton')),
                ('status', models.CharField(choices=[('non_contacte', 'Non contacté'), ('envoi_programme', 'Envoi programmé'), ('envoye', 'Envoyé'), ('erreur_envoi', "Erreur d'envoi"), ('consulte', 'Consulté'), ('confirme_sans_modification', 'Confirmé sans modification'), ('en_attente_validation', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('expire', 'Expiré')], default='non_contacte', max_length=30, verbose_name='Statut')),
                ('delivery_channel', models.CharField(blank=True, choices=[('email', 'E-mail'), ('courrier', 'Courrier'), ('telephone', 'Téléphone'), ('accueil', 'Accueil physique')], max_length=20, verbose_name='Canal prévu')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Première consultation')),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'ouvertures")),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière consultation')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='campagnes.updatecampaign', verbose_name='Campagne')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structures.structure', verbose_name='Fiche')),
            ],
            options={
                'verbose_name': 'Invitation à vérifier',
                'verbose_name_plural': 'Invitations à vérifier',
                'ordering': ['structure__nom_structure', 'structure__nom', 'structure__prenom'],
            },
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='campagnes.verificationinvitation', verbose_name='Invitation'),
        ),
        migrations.AddConstraint(
            model_name='verificationinvitation',
            constraint=models.UniqueConstraint(fields=('campaign', 'structure'), name='campagnes_invitation_unique_campagne_fiche'),
        ),
    ]
