# Generated by Django 6.0.7 on 2026-08-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecampaign',
            name='test_emails',
            field=models.CharField(blank=True, help_text='2-3 adresses séparées par des virgules, utilisées uniquement en mode test.', max_length=500, verbose_name='Adresses e-mail de test'),
        ),
        migrations.AddField(
            model_name='updatecampaign',
            name='test_mode',
            field=models.BooleanField(default=False, help_text='Les e-mails sont envoyés uniquement aux adresses de test, jamais aux personnes.', verbose_name='Mode test'),
        ),
    ]
